import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import GoogleTagManager from "./components/GoogleTagManager";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "44Rmy3ZKT9r-Dc0zZPvE-nZVsYkNf7X3_J0oumNUXmc",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManager />
      </head>
      <body className={`${dmSans.className} bg-bgDark antialiased`}>
        {children}
      </body>
    </html>
  );
}
